#!/usr/bin/env python3
"""Build client/src/data/questions.ts from the JSON question banks.

Sources:
  - script/existing_questions.json  (snapshot of the original hand-made bank)
  - ../banks/*.json                 (new validated banks, schema {q,a,points,image})
  - ../banks/movies.json            (array of movie titles for «بدون كلام»)

Run:  python3 script/build_questions.py
"""
import json, pathlib, re, unicodedata

APP = pathlib.Path(__file__).resolve().parent.parent
BANKS = APP.parent / "banks"
OUT = APP / "client/src/data/questions.ts"

# category key -> (name, emoji, bank file, hasImages)
CATS = [
    ("islam",     "إسلاميات",            "🕌",  "islamiyat.json",  False),
    ("geo",       "جغرافيا وعواصم",       "🗺️",  "geography.json",  False),
    ("flags",     "أعلام",                "🚩",  "flags.json",      True),
    ("currency",  "عملات ودول",           "💰",  "currencies.json", False),
    ("history",   "تاريخ وشخصيات",        "🏛️",  "history.json",    False),
    ("leaders",   "رؤساء الدول",          "🎖️",  "leaders.json",    False),
    ("inventors", "مخترعون ومكتشفون",     "💡",  "inventors.json",  False),
    ("science",   "علوم وجسم الإنسان",    "🔬",  "science.json",    False),
    ("animals",   "حيوانات وأصواتها",     "🦁",  "animals.json",    False),
    ("general",   "ثقافة عامة ومنوعات",   "🎭",  "general.json",    False),
    ("reversed",  "كلمات معكوسة",         "🔁",  "reversed.json",   False),
    ("wadda7",    "وضح شوية",             "🌫️",  "wadda7.json",     True),
    ("zoom",      "زوم",                  "🔎",  "zoom.json",       True),
    ("logos",     "شعارات عالمية",         "🏷️",  "logos_bank.json", True),
    ("firstletter","حروف",                "🔤",  "firstletter_bank.json", False),
    ("moving",    "حروف متحركة",          "🎈",  "moving.json",     False),
]

DIAC = re.compile(r"[\u064B-\u0652\u0670\u0640]")


def norm(t: str) -> str:
    t = unicodedata.normalize("NFKC", t)
    t = DIAC.sub("", t)
    t = t.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا").replace("ٱ", "ا")
    t = t.replace("ى", "ي").replace("ة", "ه").replace("ؤ", "و").replace("ئ", "ي")
    t = re.sub(r"[^\w\u0600-\u06FF]+", "", t)
    return t


existing = json.loads((APP / "script/existing_questions.json").read_text(encoding="utf-8"))
existing_by_key = {c["key"]: c for c in existing}


def load(name):
    p = BANKS / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else []


def esc(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


out_cats = []
report = []
for key, name, emoji, bank, has_images in CATS:
    rows = []
    seen = set()
    for src in (existing_by_key.get(key, {}).get("questions", []), load(bank)):
        for r in src:
            pts = int(r["points"])
            if pts not in (200, 400, 600):
                pts = 400
            q = (r["q"] or "").strip()
            a = (r["a"] or "").strip()
            img = r.get("image") or None
            letter = r.get("letter") or None
            if not q or not a:
                continue
            sig = (norm(q), norm(a)) if not img else (norm(q), norm(a), img)
            if sig in seen:
                continue
            seen.add(sig)
            rows.append({"points": pts, "q": q, "a": a, "image": img, "letter": letter})
    # stable ids by position
    for i, r in enumerate(rows, 1):
        r["id"] = f"{key}-{i}"
    dist = {p: sum(1 for r in rows if r["points"] == p) for p in (200, 400, 600)}
    report.append((key, name, len(rows), dist, has_images))
    out_cats.append({"key": key, "name": name, "emoji": emoji, "hasImages": has_images, "questions": rows})

movies = load("movies.json")

lines = [
    "// AUTO-GENERATED by script/build_questions.py — do not edit by hand.",
    "export type Difficulty = 200 | 400 | 600;",
    "export interface Question { id: string; q: string; a: string; points: Difficulty; image?: string; letter?: string }",
    "export interface Category { key: string; name: string; emoji: string; hasImages?: boolean; questions: Question[] }",
    "",
    "export const CATEGORIES: Category[] = [",
]
for c in out_cats:
    lines.append("  {")
    lines.append(f'    key: {esc(c["key"])},')
    lines.append(f'    name: {esc(c["name"])},')
    lines.append(f'    emoji: {esc(c["emoji"])},')
    if c["hasImages"]:
        lines.append("    hasImages: true,")
    lines.append("    questions: [")
    for r in c["questions"]:
        img = f', image: {esc(r["image"])}' if r["image"] else ""
        letter = f', letter: {esc(r["letter"])}' if r.get("letter") else ""
        lines.append(
            f'      {{ id: {esc(r["id"])}, points: {r["points"]}, q: {esc(r["q"])}, a: {esc(r["a"])}{img}{letter} }},'
        )
    lines.append("    ],")
    lines.append("  },")
lines.append("];")
lines.append("")
lines.append("export const CATEGORY_BY_KEY: Record<string, Category> = Object.fromEntries(")
lines.append("  CATEGORIES.map((c) => [c.key, c]),")
lines.append(");")
lines.append("")
lines.append("export const TOTAL_QUESTIONS = CATEGORIES.reduce((n, c) => n + c.questions.length, 0);")
lines.append("")
lines.append("/** أفلام ومسلسلات لفقرة «بدون كلام» */")
lines.append("export const MOVIES: string[] = [")
for m in movies:
    lines.append(f"  {esc(m)},")
lines.append("];")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")

total = sum(r[2] for r in report)
print(f"{'key':10} {'questions':>9}  200/400/600")
for key, name, n, dist, hi in report:
    print(f"{key:10} {n:9}  {dist[200]}/{dist[400]}/{dist[600]}  {name}{'  [images]' if hi else ''}")
print(f"TOTAL categories={len(report)} questions={total} movies={len(movies)}")
